name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

jobs: 
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Setup Python 3.11
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Generate coverage report
        run: |
          pip install pytest pytest-cov
          pip install -r requirements.txt
          python -m pytest --cov=shell_craft --cov build --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: codecov-umbrella
          verbose: true
          files: coverage.xml