name: Run version bump, if version changes publish a release.

on:
  push:
    branches:
      - trunk

jobs:
  release:
    permissions:
      contents: write
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install semver
          pip install pydantic

      - name: Get current version
        run: |
          VERSION=$(python build/semver_bump.py --version)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Current version is $VERSION"

      - name: Increment version
        run: |
          python build/semver_bump.py v${{ env.VERSION }}
          NEW_VERSION=$(python build/semver_bump.py --version)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Bumped version from ${{ env.VERSION }} to $NEW_VERSION"

      - name: Commit version bump
        run: |
          git add pyproject.toml
          git commit -m "Bump version to v${{ env.NEW_VERSION }}"
          git push
          echo "Committed version bump to ${{ env.NEW_VERSION }}"
        if: ${{ env.NEW_VERSION != env.VERSION }}

      - name: Generate changelog
        run: |
          CHANGELOG=$(python build/change_log.py v${{ env.VERSION }})
          echo "CHANGELOG=$CHANGELOG" >> $GITHUB_ENV
          echo "Changelog is ${{ env.CHANGELOG }}"
        if: ${{ env.NEW_VERSION != env.VERSION }}

      - name: Create release tag
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: v${{ env.NEW_VERSION }}
          body: ${{ env.CHANGELOG }}
          prerelease: true
        if: ${{ env.NEW_VERSION != env.VERSION }}
        